[tools]
"github:JohnnyMorganz/StyLua" = "2.5.2"
"github:Kampfkarren/selene" = { version = "0.31.0", bin = "selene" }
"github:UpliftGames/wally" = "0.3.2"
"github:lune-org/lune" = "0.10.5"
"github:rojo-rbx/rojo" = "7.7.0"
node = "latest"
