name = "riptide/core"
version = "0.9.0-maelstrom.1"
description = "A lightweight and professional framework for Roblox."
license = "MIT"
authors = ["Riptide Development Group"]
repository = "https://github.com/riptide-project/framework"

includes = ["pesde.toml", "README.md", "LICENSE", "src/**"]

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.4", target = "luau" }
