name = "riptide/core"
version = "0.9.0-maelstrom.2"
description = "A strict Luau framework for Roblox with side-specific APIs, typed networking/state, module lifecycle orchestration, and sandboxed plugins."
license = "MIT"
authors = ["Riptide Development Group (https://github.com/riptide-project)"]
repository = "https://github.com/riptide-project/framework"
private = false

includes = [
	"src/**",
	"README.md",
	"LICENSE",
	"pesde.toml",
]

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.4", target = "luau" }
